import {
  createInvoice,
  getInvoice,
  qboQuery,
  updateInvoice,
  voidInvoice,
  type QboClientDeps,
} from "../qbo/client";

export interface QboRef {
  Id: string;
  SyncToken: string;
}

// The invoice operations the processor needs, abstracted so tests inject an
// in-memory fake instead of hitting Intuit.
export interface QboInvoiceOps {
  findByDocNumber(docNumber: string): Promise<QboRef | undefined>;
  create(invoice: Record<string, unknown>, requestId: string): Promise<QboRef>;
  read(id: string): Promise<QboRef>;
  update(invoice: Record<string, unknown>): Promise<QboRef>;
  voidInvoice(id: string, syncToken: string): Promise<void>;
}

interface InvoiceEnvelope {
  Invoice: QboRef;
}
interface QueryEnvelope {
  QueryResponse: { Invoice?: QboRef[] };
}

// The real implementation, wrapping the QBO Accounting client. Internal ids are
// generated by us (alphanumeric + dash), so they're safe to inline in the query.
export function createQboInvoiceOps(deps: QboClientDeps): QboInvoiceOps {
  return {
    async findByDocNumber(docNumber) {
      const res = (await qboQuery(
        deps,
        `select Id, SyncToken from Invoice where DocNumber = '${docNumber}'`,
      )) as QueryEnvelope;
      return res.QueryResponse.Invoice?.[0];
    },
    async create(invoice, requestId) {
      const res = (await createInvoice(deps, invoice, requestId)) as InvoiceEnvelope;
      return res.Invoice;
    },
    async read(id) {
      const res = (await getInvoice(deps, id)) as InvoiceEnvelope;
      return res.Invoice;
    },
    async update(invoice) {
      const res = (await updateInvoice(deps, invoice)) as InvoiceEnvelope;
      return res.Invoice;
    },
    async voidInvoice(id, syncToken) {
      await voidInvoice(deps, id, syncToken);
    },
  };
}
